# Tensor 创建

In [59]:
import torch
import numpy as np

## 一 使用随机值或常量值

### 1.1 使用随机值

In [51]:
shape = (2, 3,)
tensor_rand = torch.rand(shape)
tensor_rand

tensor([[0.4992, 0.0379, 0.2174],
        [0.4890, 0.1022, 0.9435]])

### 1.2 使用常量0

In [52]:
shape = (3, 3,)
tensor_zeros = torch.zeros(shape)
tensor_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### 1.3 使用常量1

In [53]:
shape = (3, 2,)
tensor_ones = torch.ones(shape)
tensor_ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

## 二 直接从数据创建

In [50]:
data = [[1, 2], [3, 4]]
tensor_data = torch.tensor(data)
tensor_data

tensor([[1, 2],
        [3, 4]])

## 三 从另一个张量创建

In [55]:
tensor_rand_like = torch.rand_like(tensor_zeros)
tensor_rand_like

tensor([[0.5559, 0.2070, 0.5764],
        [0.8717, 0.9914, 0.7064],
        [0.4187, 0.5707, 0.5561]])

In [56]:
tensor_zeros_like = torch.zeros_like(tensor_ones)
tensor_zeros_like

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [57]:
tensor_ones_like = torch.ones_like(tensor_rand)
tensor_ones_like

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## 四 从 NumPy array

In [60]:
np_data = [[1, 2], [3, 4]]
np_array = np.array(np_data)
np_array

array([[1, 2],
       [3, 4]])

In [61]:
tensor_numpy = torch.from_numpy(np_array)
tensor_numpy

tensor([[1, 2],
        [3, 4]])